spring:
  application:
    name: user
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: true
    fetch-registry: false

logging:
  config: classpath:logback.xml
